### ISSUE TITLE
Broken link to python-ideas mailing list archive

### ISSUE THREAD

**Issue by black-web-dev** [topstar-dev/typescript-paperboy#3]
Describe the bug
On the python.org "Mailing Lists" page, the hyperlink to ActiveState's archive of the python-ideas mailing list (URL: https://code.activestate.com/lists/python-ideas/) is broken.

To Reproduce

Go to https://www.python.org/community/lists/
Scroll down to 'python-ideas mailing list'
Click the 'ActiveState archive of python-ideas' hyperlink
See HTTP 404 error
Expected behavior
The hyperlink should be updated, or perhaps replaced/removed if ActiveState no longer archives the list.

Screenshots
N/A

Desktop (please complete the following information):
N/A

Smartphone (please complete the following information):
N/A

Additional context
N/A

**Comment by black-web-dev** [comment]
...

**Comment by topstar-dev** [comment]
Closed this issue  #2
